### ISSUE TITLE
Harmony correction for two variables

### ISSUE THREAD

**Issue by chi-raag** [immunogenomics/harmony#123]
If there were two variables that one would want to correct for (X and Y), would there be an effective difference between using harmony like so (code below involves Seurat wrapper):

```
data <- runHarmony(data, c("X", "Y"))
```

vs

``` 
data <- runHarmony(data, "X") %>%
  runHarmony(data, "Y")
```

**Comment by ilyakorsunsky** [comment]
Hi @chi-raag, 

I would personally use the first one. However, I can see potential benefits to using both. 

1) **Simultaneous.** Harmony models the effect of any variables you pass on cells' low dimensional embeddings. In practice, if I pass all relevant sources of variation, I will model the cells better and in that sense, be better positioned to more accurately remove the effect of "X" and "Y". If I do Harmony over "X", I integrate over an imperfect model and then if I run Harmony again over Y on the harmonized embeddings, I will fit another imperfect model. Note that the simultaneous approach works even when covariates are nested! This is because we used ridge regression to shrink our effect estimates, a common approach to deal with confounded covariates. 

2) **Stepwise.** Here, you get two answers: one with "X" removed and one with both "X" and "Y" removed. If both embeddings are useful for your study, this could be a big advantage. I would eventually like to add a feature in Harmony where you fit the full model (i.e. with "X" and "Y") and then once the model is fit, remove the effect of "X", "Y", or both. This is unfortunately not feasible in the current release. 

Hope this helps and thank you for your patience! 

Best, 
Ilya
