### ISSUE TITLE
Cross-Species integration

### ISSUE THREAD

**Issue by jad362** [immunogenomics/harmony#129]
Hello,

Love your integration tool, super nice to have a scalable method for batch correction in single cell. I was wondering if you could speak to Harmony's ability to perform a cross-species batch correction? There doesn't appear to be any documentation on the matter in the publication or vignettes. I know Seurat's CCA method can perform the integration but I prefer the scalability of harmony's method which is why I am asking.

Thanks!

**Comment by ilyakorsunsky** [comment]
Hi @jad362, 

I and others have certainly used Harmony for cross-species integration, so I encourage you to give it a shot! The main challenge is to first convert the mouse and human genes into the same gene space, so that you can represent all mouse and human cells in one matrix. Once you do that, then you treat species as any other variable. Note that if you have multiple batches within your human and mouse datasets, you may want to harmonize over both species and batch. 

Hope that helps! 

Best, 
Ilya
