### ISSUE TITLE
random state

### ISSUE THREAD

**Issue by wangjiawen2013** [immunogenomics/harmony#13]
Dear,
Will harmony support scanpy in later days ? 
The correction expression matrix is different when re-run harmony every time, they're unreproducible. It seems that there are some random factors in harmony algorithm, can you fix it and add some help documentations on the detailed usage ?

**Comment by ilyakorsunsky** [comment]
Dear @wangjiawen2013, 

Great suggestions! 

There have been several requests for scanpy support. I have not started this; I will look into what it would take. 

For reproducibility, I'm working on this feature now. In the meantime, I've found that setting the random seed in R (e.g. set.seed(1)) before running Harmony gets you 90% of the way there. This is because Harmony now initializes clusters with base R kmeans. When these initial clusters are the same, the final Harmony answer is also often consistent. 

Thanks for your patience!

Best, 
Ilya

**Comment by wangjiawen2013** [comment]
Thanks for you powerful tool. I integrated harmony into my scanpy pipeline in a customized manner now, however, I hope you can release a version that compatible well with scanpy.

**Comment by ilyakorsunsky** [comment]
Dear @wangjiawen2013, 

In more recent tests, I've found that `set.seed()` works both initialization and Harmony clustering. This code demonstrates that. When you change either one of the seeds in cluster initialization or cluster updates, the result will be slightly different. 

```{r}
library(harmony)
data(cell_lines_small)

with(cell_lines_small, {    
    ## seed affects cluster initialization
    set.seed(1)
    res1 <<- HarmonyMatrix(
        scaled_pcs, meta_data, 'dataset', 
        do_pca=FALSE, verbose=FALSE, return_object=TRUE, max.iter.harmony=0
    )

    ## seed affects cluster initialization
    set.seed(1)
    res2 <<- HarmonyMatrix(
        scaled_pcs, meta_data, 'dataset', 
        do_pca=FALSE, verbose=FALSE, return_object=TRUE, max.iter.harmony=0
    )

})
max(abs(res1$Z_corr - res2$Z_corr))


## seed affects harmony updates in `update_R()`
set.seed(1)
.x <- harmony:::harmonize(res1, 10, FALSE)

## seed affects harmony updates in `update_R()`
set.seed(1)
.x <- harmony:::harmonize(res2, 10, FALSE)

max(abs(res1$Z_corr - res2$Z_corr))
```

Best, 
Ilya
