### ISSUE TITLE
max.iter.harmony parameter adjustment for big datasets

### ISSUE THREAD

**Issue by NK-HD** [immunogenomics/harmony#130]
Hey,

thanks for developing this cool package. I am currently working on integration of a rather bigger dataset (30samples, 76k cells) and was wondering on how to best adjust the RunHarmony parameters for this. Should I for example increase the maximal ierations to account for the higher number of different datasets?

Are there any recommendations for this or is it fine to just increase the parameters basically until harmony converges (e.g. increasing to 50 iterations: Harmony converges after 15)

Or are there any other parameters you would recommend?

thanks so much for your guidance!
Best, Niklas

**Comment by ilyakorsunsky** [comment]
Dear @NK-HD, 

To be confident about the convergence parameters, I would suggest two things. First, I would set `plot_convergence=TRUE` to see the changes in objective score over iterations. Second, since the objective function of the clustering is not always aligned with the objective function of the correction (see discussion of cosine distance, something to fix in the next Harmony versions), I set `epsilon.cluster=-Inf` and `epsilon.harmony=-Inf` to prevent early stopping. 

Hope that helps! 

Best, 
Ilya

**Comment by NK-HD** [comment]
Thanks for the quick reply! Will adjust the function accoridingly. Just to understand it correctly: 
with the settings you described, there will be no early stopping at all right?
So on what basis should one then set the maximal number of harmony iterations in order to be sure of correct integration?

Best, Niklas

**Comment by ilyakorsunsky** [comment]
Yup, that's right! This should eliminate early stopping, so it might run longer than needed. To decide on how many iterations total, I would look at the convergence plot and make sure that the score is not changing in later iterations.
