### ISSUE TITLE
Choosing appropriate harmony dimensions

### ISSUE THREAD

**Issue by ShuyangZhao** [immunogenomics/harmony#15]
Hi, 
Thanks for developing harmony, it is definitely a great tool for sample integration.
One question i have is that, i know there are ```PCElbowPlot``` for viewing the SD change for each PCs, and ```MetageneBicorPlot``` for CCA to view the correlation strength for each CC. I would like to know is there a function such as these for harmony to visualize a certain metrics to select the most appropriate harmony dimension for tSNE and clustering other than ```DimHeatmap``` .

Thanks,
Shuyang

**Comment by ilyakorsunsky** [comment]
Dear @ShuyangZhao,  

I agree, this is an important question! I usually compute Harmony on all PCA dimensions and use all Harmony dimensions for downstream analysis. Including lower variance components usually doesn't affect the final answers, since the lower variance components have less weight. 

Best, 
Ilya

**Comment by ShuyangZhao** [comment]
@ilyakorsunsky Thanks!
