### ISSUE TITLE
Error in Runharmony

### ISSUE THREAD

**Issue by evaniali** [immunogenomics/harmony#158]
Thanks for your tools!
I met an error like this. And I can't found the harmony results. 
Error: (converted from warning) Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony; see ?make.names for more details on syntax validity

**Comment by Arsenalwins** [comment]
> Thanks for your tools! I met an error like this. And I can't found the harmony results. Error: (converted from warning) Invalid name supplied, making object name syntactically valid. New object name is Seurat..ProjectDim.RNA.harmony; see ?make.names for more details on syntax validity
I am also faced with this error,have you figured out how to solve it>

**Comment by pati-ni** [comment]
Hi @evaniali, 

This is due to the `project_dim=TRUE` in `RunHarmony()`. This runs Seurat's `ProjectDim()`. By setting this `project_dim=FALSE` you can get rid of that warning.

With later versions of Seurat this shows up as a warning... Latest Seurat v5 (still in beta this disappears). If you are still experiencing issues and want `project_dim=TRUE` I suggest you bring this issue to the Seurat's page.
