### ISSUE TITLE
Error in harmonyObj$init_cluster_cpp

### ISSUE THREAD

**Issue by yoshihiko1218** [immunogenomics/harmony#166]
Hi,

When I run normalization on Seurat object, I got following error:
```
Error in harmonyObj$init_cluster_cpp(0) :
  element-wise multiplication: incompatible matrix dimensions: 100x3 and 100x1
```
It works on some other the variables in metadata I tried but does not work on some variables. Has anyone met this error before and what might cause this?

**Comment by erikla** [comment]
Hi,
Had this same error.
This problem was resolved for me after I defined the group_by_vars variable as a factor,
(e.g. seuratObj@meta.data$library_batch <- as.factor(seuratObj@meta.data$library_batch))
Then the following statement worked:
seuratObj <- RunHarmony(object = seuratObj, group.by.vars="library_batch", verbose = T, assay.use="SCT")

**Comment by ianyfchang** [comment]
I had the same error.
I re-install harmony by devtools::install_github("immunogenomics/harmony") (re-compile C++ codes) to fix the error.

**Comment by wxpbioinfo** [comment]
> I had the same error. I re-install harmony by devtools::install_github("immunogenomics/harmony") (re-compile C++ codes) to fix the error.

Hi,I had the same error too.Could you tell me how to (re-compile C++ codes) to fix the error?
Thank you very much

**Comment by maxlarosa** [comment]
Hi, I have the same error, I re-installed with  devtools::install_github("immunogenomics/harmony") but unfortunately the error is still there.

**Comment by TC-gu** [comment]
Hi all, I struggled with the same error but only when running on a RHEL server, on my PC it worked just fine. After trying various solutions (including mentioned above) it turned out that the issue was in the Rcpp package version.
On windows I was running Rcpp_1.0.7 and on the server Rcpp_1.0.9.
I actually couldn't install the older version on the server due to some g++ compiler issues (way above my paygrade) but luckily I had an older R version installed there too with the Rcpp_1.0.7 and there Harmony worked like on my PC.

So check your Rcpp package version.

**Comment by liangxs7015** [comment]
I solved the problem by reinstallation too.

**Comment by artemisiat** [comment]
Could you please share your sessionInfo whoever solved it. It is day 3 that i am troubleshooting and it is very frustrating.

**Comment by emilepe** [comment]
Same issue for me. I'm really struggling here. After trying what @erikla suggested (https://github.com/immunogenomics/harmony/issues/166#issuecomment-1259678548), i now get:
Harmony 1/10
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Error in harmonyObj$moe_correct_ridge_cpp() : 
  addition: incompatible matrix dimensions: 8x8 and 7x7
In addition: Warning message:
In theta * (1 - exp(-(N_b/(nclust * tau))^2)) :
  longer object length is not a multiple of shorter object length

So frustrating....

**Comment by artemisiat** [comment]
for me it worked when i used a previous instance with:
R4.2
Seurat4.1.1
Rcpp1.0.8
Harmony0.1.0
Hope this helps!

**Comment by emilepe** [comment]
Thank you @artemisiat. 
I'm using R 4.2.0 / Seurat 4.3.0 / Rcpp 1.0.9 /  harmony 0.1.1
Right now, I can finally make it work but for that, I have to make the meta.data (that is integer) used to batch correct as.factor like suggested by another user with:
myRobject@meta.data$something <- as.factor(myRobject@meta.data$something)

**Comment by pariaaliour** [comment]
I have the same issue. My R version is 4.1.2 and I tried with Rcpp version 1.0.9 and 1.0.7 but it did not work. I set batch as integer in metadata and did as.factor. It still doesn't work for me. Any input on this?
Thanks,
Paria

**Comment by PerseusFu** [comment]
thanks @erikla and I solve the problem by set these data as factor.

**Comment by Angel-Wei** [comment]
I'm using R version 4.2.3 on a cluster server with OS Ubuntu 22.04.1 LTS. I had this problem when running harmony and it fixed when I uninstall harmony and reinstall it from CRAN. The reinstalled harmony is in version 0.1.1

**Comment by pati-ni** [comment]
#171 #167 #168 addressed in latest version of harmony, no workaround is needed
