### ISSUE TITLE
Bug: element-wise pow(): incompatible matrix dimensions: 100x63 and 63x1

### ISSUE THREAD

**Issue by Famingzhao** [immunogenomics/harmony#168]
I am sure that my seurat data is ok. It seems a conflict for some new versions packages.
![image](https://user-images.githubusercontent.com/79517714/194505775-7bffcbef-9367-4c82-afc0-8fd4cfb4fc69.png)

**Comment by YanRuochen1** [comment]
>hi, i meet the same problem，could you tell me how to scale it?

**Comment by HarrisHan2k** [comment]
Hi Faming,

I encountered this problem as well. It turned out to be not all the groups in the group.by.var arguments include cells (it happened when I use seurat objects that are subset of a larger one). Please check if all the groups have cells, and you can use droplevels() function to drop empty levels and that works for me.

Hope it helps!

Best,
Harris

**Comment by Famingzhao** [comment]
In fact, I had checked "group" levels, but it still did not work. I documented another solution to this problem: https://mp.weixin.qq.com/s/Q1LA_jGEsfWeCm-Uk4ZjGA. Hope can help  (if you can read Chinese).

**Comment by pati-ni** [comment]
@Famingzhao If I could guess, it would be that sampleID is seen as a number. Do you have numbers in your covariate? Casting the `sampleID`  `as.factor()` in the Seurat metadata data frame should fix this.
