### ISSUE TITLE
harmony for normalized scRNA-seq dataset

### ISSUE THREAD

**Issue by martina811** [immunogenomics/harmony#224]
Hello, I would like to integrate 2 single cell datasets, but one has the raw counts and the other one the normalized counts, is harmony suitable to integrate these two kind of datasets?

Thank you for your help.

**Comment by pati-ni** [comment]
You should definitely normalize the raw counts as you would normally (size factors, log).
For the normalized data you should figure out whether there are already log normalized. If not you should perform that step, so that variance is not driven by expression level.

This will ensure that your PCs are properly computed which harmony will use for batch correction. FYI, by default Harmony does not work with the counts data.
