### ISSUE TITLE
Harmony and Seurat - merging experiments 

### ISSUE THREAD

**Issue by fede86** [immunogenomics/harmony#44]
Hi, 
thank you for your great tool - it works very well for our experiments with relatively hight batch effect. We have two different experimental conditions (treated and untreated) with 3 replicates each, we use Seurat (v3) to merge those experiments. Do you have any suggestions/guidelines when (before or after batch-correction) and how to merge the experiments when using harmony and Seurat?

Thank you in advance!

**Comment by ilyakorsunsky** [comment]
Dear @fede86, 

I would recommend merging the datasets as soon as possible (i.e. at the raw UMI level). Because batch effects have globally non-linear effects, it is potentially dangerous to include batch information in the normalization, scaling, or PCA steps. In the manuscript, we explore the dangers of scaling each batch separately, especially when the batches have different cell types and cell type proportions. 

Hope that helps! 

Best, 
Ilya
