### ISSUE TITLE
objective function jumps

### ISSUE THREAD

**Issue by whitleyo** [immunogenomics/harmony#48]
Hi,

I've tried running harmony on a dataset of cultured cell lines and patient tumour samples. There were about 26 patient cell culture lines, each representing a separate scRNA experiment, as well as several tumours, each having at least one replicate scRNA experiment. PCA was determined using variable genes found via the mean.var.plot method. It appears that when I run harmony using default settings, there's a jump in the objective function. I don't think this is expected behavior, so I was wondering if there were any recommendatations you had for diagnosing what might be going wrong here.

Here's the plot of objective function vs iterations:

![image](https://user-images.githubusercontent.com/25909144/63807809-7c9cd200-c8ec-11e9-86c6-1e15e96dc21d.png)

Here's a PCA plot of the data prior to correction:

![image](https://user-images.githubusercontent.com/25909144/63807870-a6ee8f80-c8ec-11e9-89ff-15574cf672e5.png)

And the harmony coordinates after:

![image](https://user-images.githubusercontent.com/25909144/63807887-b372e800-c8ec-11e9-9a0c-b89e9b7c0590.png)

I've found that genes differentially expressed between bulk tumours and cell lines (found using bulk RNA-seq data) are indeed differentially expressed between the tumour and cell line cells for this scRNA data, so my hunch is that most of the differences observed between tumour and line cells are due to actual biological effects.

Thanks for any help you might be able to give.

I can give you sesssionInfo details or code upon further request if necessary.

**Comment by ilyakorsunsky** [comment]
Dear @whitleyo, 

Unfortunately, this is a potential issue with the current Harmony implementation. From my experience, this happens because clustering uses cosine distance while correction (implicitly) uses Euclidean distance. I discuss this briefly in the manuscript:

*Caveat. This section assumes the modeled data are orthogonal and each normally distributed. This is not true for the log2 normalized data used in spherical clustering. Regression in this space requires the estimation and interpolation of rotation matrices, a difficult problem. We instead perform batch correction in the unnormalized space. The corrected data Z^ are then log2-normalized for the next iteration of clustering.*

I am working on several solutions to remove the need for cosine distance in the clustering step but do not have any implementations that fix this yet.

Best,
Ilya

**Comment by annamath** [comment]
Hello, Thank you very much for harmony and the support :) 

I am having the same problem-are there any updates? 
Also, could you maybe elaborate a bit more on your previous comment: 
 _From my experience, this happens because clustering uses cosine distance while correction (implicitly) uses Euclidean distance._
This is a bit confusing for me. I don't understand why clustering matters at this stage since the 'input' for harmony is dim.reduced data (e.g. PCA). 

Bellow are more details: 
```
sgGFP_integrated <- RunHarmony(
  object = sample1_seurat,
  group.by.vars = 'Donors',
  assay.use = 'RNA',
  plot_convergence = TRUE)
```
> Harmony 1/10
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Harmony 2/10
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Harmony converged after 2 iterations
> Error in data.use %*% cell.embeddings : non-conformable arguments

Based on the issue here I then tried:
https://github.com/satijalab/seurat/issues/1849
```
sgGFP_integrated <- RunHarmony(
  object = sample1_seurat,
  group.by.vars = 'Donors',
  assay.use = 'SCT',
  plot_convergence = TRUE)

```
> Harmony 1/10
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Harmony 2/10
> 0%   10   20   30   40   50   60   70   80   90   100%
> [----|----|----|----|----|----|----|----|----|----|
> **************************************************|
> Harmony converged after 2 iterations

![sgGFP_harmony_convergence](https://user-images.githubusercontent.com/38502371/81927429-ea586d80-95e3-11ea-9bf0-6d88214b7403.png)

Thank you in advance! 
Anna

**Comment by qjcatherine** [comment]
hi, I am having the same problem and I wonder under such circumstance, harmony is not suitable for the dataset analysis? Is is?

**Comment by LukeJMH** [comment]
Hello, I am also having this issue. Its confusing as going by the dimplot the process seems to have worked, but I also got this plot
![Harmony plot](https://user-images.githubusercontent.com/108405928/186232933-c7895b56-59a6-41c1-b6cf-7a63f4e55f1e.jpeg)
 If the RunHarmoy function returns this plot, can the results be trusted?
