### ISSUE TITLE
About the convergence plot

### ISSUE THREAD

**Issue by JPingLin** [immunogenomics/harmony#67]
Hi, thank you for the amazing tool! 

I have a question about the convergence plot interpretation. Is it that objective function the lower the better and the harmony_idx the higher the better? Sometimes, I will have a plot like this, where in the final iteration the dots jumped up and the message says it is converged. Is it suppose to be like this? 
Thank you!

![harmony](https://user-images.githubusercontent.com/50379176/72909406-f6eb4a00-3d04-11ea-898e-475fb3e632eb.png)

**Comment by ilyakorsunsky** [comment]
Dear @JPingLin, 

Unfortunately, this is a potential issue with the current Harmony implementation. From my experience, this happens because clustering uses cosine distance while correction (implicitly) uses Euclidean distance. I discuss this briefly in the manuscript: 

*Caveat. This section assumes the modeled data are orthogonal and each normally distributed. This is not true for the log2 normalized data used in spherical clustering. Regression in this space requires the estimation and interpolation of rotation matrices, a difficult problem. We instead perform batch correction in the unnormalized space. The corrected data Z^ are then log2-normalized for the next iteration of clustering.*

I am working on several solutions to remove the need for cosine distance in the clustering step but do not have any implementations that fix this yet. 

Best, 
Ilya

**Comment by parvathisudha** [comment]
Hi,

I have a question regarding this. So, is it a good idea to select the number of dimensions based on the convergence plot? If so, can you please tell me how to select that?

Thank you!
