### ISSUE TITLE
Correct batch effects between replicates or treatment or both

### ISSUE THREAD

**Issue by w2niva** [immunogenomics/harmony#68]
I have a 10X single-cell dataset consisting of four treatments and two replicates (8 samples). There are batch effects between my samples. To do batch correction between my samples, what is ideal -
to do batch correction across all eight samples or 
do batch correction only between biological replicates of the same treatment and use corrected treatment- specific matrix for further analysis to compare between treatments.

**Comment by ilyakorsunsky** [comment]
Dear @w2niva, 

That's a great question. In general, my strategy would be to Harmonize over all 8 samples and identified shared cell types among all treatments. Then within each cell type, I would look for treatment-specific differences with differential expression analysis. 

I would avoid the strategy of comparing two different Harmonized datasets, because Harmony does not correct gene expression values and PC embeddings are not comparable across two PC analyses. The design of Harmony is rather to model everything in one space and then decide which effects to remove for downstream clustering, UMAP, etc. 

Hope that helps! 

Best, 
Ilya
